name: Проверка кода (CI)
on:
  pull_request:
    branches: [ main ]

jobs:
  test-button:
    runs-on: ubuntu-latest
    steps:
      - name: Скачиваем код
        uses: actions/checkout@v4

      - name: Проверяем наличие кнопки
        run: |
          if grep -q "<button>" index.html; then
            echo "Тест пройден: кнопка на месте!"
          else
            echo "Ошибка: кнопка не найдена в index.html!" && exit 1
          fi
